### ISSUE TITLE
Request for file removal: trajanPro.otf

### ISSUE THREAD

**Issue by miguelsousa** [SuneBear/SB-Blog#1]
When using http://www.getthefont.com/, I found your font file [trajanPro.otf](http://github.com/SuneBear/SB-Blog/blob/cc19ab10697704be4f70c0e4998c404cec9c74e7/archived/2014/resume/font/trajanPro.otf), uploaded in this repository. I believe that this file was uploaded here by mistake, because its license does not allow distribution through a public website.

I would like to kindly ask you to remove this font file from the repository.

Kind regards,

**Comment by SuneBear** [comment]
Oooooooh Nooooooo, shame on me ignore the font license. I am really sorry that I downloaded and loaded it two years ago in the public. The font has been removed in the lastest version. Thanks for your mention : )

**Comment by SuneBear** [comment]
7b47f7eb32b7296ea0f1eabdaaf1d3db01cd0d6c

**Comment by SuneBear** [comment]
#7b47f7eb32b7296ea0f1eabdaaf1d3db01cd0d6c
